name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Kód letöltése a repóból
      - name: Checkout code
        uses: actions/checkout@v4

      # JDK 23 beállítása a Zulu disztribúcióval
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'zulu'

      # Gradle függőségek gyorsítótárazása
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Gradle Wrapper futtathatóvá tétele
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Egységtesztek futtatása
      - name: Run unit tests
        run: ./gradlew test

      # Buildelés a Gradle bootJar paranccsal
      - name: Build with Gradle bootJar
        run: ./gradlew bootJar

      # JAR feltöltése artifaktként (opcionális)
      - name: Upload JAR artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: build/libs/*.jar
